version: '3.8'

services:
  backend:
    #image: rag-api-image
    build:
      context: app
      dockerfile: Dockerfile
    container_name: rag-api-app
    ports:
      - "5000:5000"

    volumes:
      - .:/code
    environment:
      FLASK_APP: app/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development  # Add this line
      PYTHONUNBUFFERED: 1
    command: flask run --debug

  frontend:
    #image: rag-frontend-image
    build:
      context: page
      dockerfile: Dockerfile
    container_name: rag-frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./page:/page
    environment:
      NODE_ENV: development
    command: npm start
    
